VolvoTrucks/Models/ErrorViewModel.cs
using System;

namespace VolvoTrucks.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VolvoTrucks/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VolvoTrucks.Models;

namespace VolvoTrucks.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VolvoTrucks/Controllers/TrucksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VolvoTrucks.Data.Context;
using VolvoTrucks.Domain.Contract;
using VolvoTrucks.Repository.Model;

namespace VolvoTrucks.Controllers
{
    public class TrucksController : Controller
    {
        private ITruckBusiness _truckBusiness;

        public TrucksController(ITruckBusiness truckBusiness)
        {
            _truckBusiness = truckBusiness;
        }

        // GET: Trucks
        public async Task<IActionResult> Index()
        {

            var volvo = _truckBusiness.Getall();
            return View(await volvo);
        }

        // GET: Trucks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var truck = await _truckBusiness.GetById(id.Value);

            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // GET: Trucks/Create
        public IActionResult Create()
        {
            ViewData["TruckModelId"] = new SelectList(_truckBusiness.GetAllModels(), "Id", "Name");
            return View();
        }

        // POST: Trucks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ManufactureYear,ModelYear,TruckModelId")] Truck truck)
        {
            if (truck.ManufactureYear != DateTime.Now.Year)
                ModelState.AddModelError("ManufactureYear", "Set a valid Manufacture Year!");

            if (truck.ModelYear != DateTime.Now.Year && truck.ModelYear != DateTime.Now.Year + 1)
                ModelState.AddModelError("ModelYear", "Set a valid Model Year!");

            if (ModelState.IsValid)
            {
                await _truckBusiness.Save(truck);
                return RedirectToAction(nameof(Index));
            }
            ViewData["TruckModelId"] = new SelectList(_truckBusiness.GetAllModels(), "Id", "Name", truck.TruckModelId);
            return View(truck);
        }

        // GET: Trucks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var truck = await _truckBusiness.GetById(id.Value);
            if (truck == null)
            {
                return NotFound();
            }
            ViewData["TruckModelId"] = new SelectList(_truckBusiness.GetAllModels(), "Id", "Name", truck.TruckModelId);
            return View(truck);
        }

        // POST: Trucks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ManufactureYear,ModelYear,TruckModelId")] Truck truck)
        {
            if (id != truck.Id)
            {
                return NotFound();
            }

            if(truck.ManufactureYear != DateTime.Now.Year)
                ModelState.AddModelError("ManufactureYear", "Set a valid Manufacture Year!");

            if (truck.ModelYear != DateTime.Now.Year && truck.ModelYear != DateTime.Now.Year + 1)
                ModelState.AddModelError("ModelYear", "Set a valid Model Year!");

            if (ModelState.IsValid)
            {
                try
                {
                    await _truckBusiness.Update(truck);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TruckExists(truck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TruckModelId"] = new SelectList(_truckBusiness.GetAllModels(), "Id", "Name", truck.TruckModelId);
            return View(truck);
        }

        // GET: Trucks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var truck = await _truckBusiness.GetById(id.Value);
            if (truck == null)
            {
                return NotFound();
            }

            return View(truck);
        }

        // POST: Trucks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var truck = await _truckBusiness.GetById(id);
            await _truckBusiness.Delete(truck);
            return RedirectToAction(nameof(Index));
        }

        private bool TruckExists(int id)
        {
            return _truckBusiness.Exists(id);
        }
    }
}

VolvoTrucks/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

VolvoTrucks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VolvoTrucks</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VolvoTrucks</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trucks" asp-action="Index">Trucks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - VolvoTrucks - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

VolvoTrucks/Views/Trucks/Create.cshtml
@model VolvoTrucks.Repository.Model.Truck

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Truck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ManufactureYear" class="control-label"></label>
                <input asp-for="ManufactureYear" class="form-control" />
                <span asp-validation-for="ManufactureYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TruckModelId" class="control-label"></label>
                <select asp-for="TruckModelId" class ="form-control" asp-items="ViewBag.TruckModelId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VolvoTrucks/Views/Trucks/Delete.cshtml
@model VolvoTrucks.Repository.Model.Truck

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TruckModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TruckModel.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VolvoTrucks/Views/Trucks/Details.cshtml
@model VolvoTrucks.Repository.Model.Truck

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Truck</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManufactureYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManufactureYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TruckModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TruckModel.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VolvoTrucks/Views/Trucks/Edit.cshtml
@model VolvoTrucks.Repository.Model.Truck

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Truck</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ManufactureYear" class="control-label"></label>
                <input asp-for="ManufactureYear" class="form-control" />
                <span asp-validation-for="ManufactureYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TruckModelId" class="control-label"></label>
                <select asp-for="TruckModelId" class="form-control" asp-items="ViewBag.TruckModelId"></select>
                <span asp-validation-for="TruckModelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VolvoTrucks/Views/Trucks/Index.cshtml
@model List<VolvoTrucks.Repository.Model.Truck>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ManufactureYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ModelYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().TruckModel)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ManufactureYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TruckModel.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>